### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by usUpal** [ramidzamzam/charCnnRnn_embedding#4]
I was implementing this and stuck in this error. I did dataset/train & dataset/test accordingly. 
`<<<<<<<<<<<<<<< Start training >>>>>>>>>>>>>>>>>
Create train dataset from - .../dataset/train
ImgDataset load images from - .../dataset/train/*.png
Train dataset size - 0
Create dataloader batches=20 and workers=0
Traceback (most recent call last):
  File "/content/models/conv_autoencoder/train.py", line 124, in <module>
    main()
  File "/content/models/conv_autoencoder/train.py", line 119, in main
    train(input_folder, output_folder, float(lr), int(epochs))
  File "/content/models/conv_autoencoder/train.py", line 36, in train
    train_loader = DataLoader(train_data, batch_size=batch_size, num_workers=num_workers, shuffle=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by ramidzamzam** [comment]
Check this "Train dataset size - 0 ..."

**Comment by usUpal** [comment]
Thanks.. It was my silly mistake. 
Now got this one...
<<<<<<<<<<<<<<< Start training >>>>>>>>>>>>>>>>>
Create train dataset from - ./dataset/train
ImgDataset load images from - ./dataset/train/*.png
Train dataset size - 19
Create dataloader batches=16 and workers=0
Conv2d(16, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
x size: `torch.Size([16, 3, 64, 64])`
Traceback (most recent call last):
  File "./models/conv_autoencoder/train.py", line 124, in <module>
    main()
  File "./models/conv_autoencoder/train.py", line 119, in main
    train(input_folder, output_folder, float(lr), int(epochs))
  File "./models/conv_autoencoder/train.py", line 60, in train
    outputs, encoder_output = model(images, encoder_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/e/NSU-FALL21/CSE499A.2/custom_char_cnn_rnn/charCnnRnn_embedding/models/conv_autoencoder/models.py", line 27, in forward
    `x = self.pool(F.relu(self.conv1(x)))`  <--**in this line, something wrong is happening**
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
`RuntimeError: Given groups=1, weight of size [16, 1, 3, 3], expected input[16, 3, 64, 64] to have 1 channels, but got 3 channels instead`

**Comment by Faisal-NSU** [comment]
@ramidzamzam  In point number 2,  /images_data.json file is needed. Could you show or provide an example of that JSON file? I am working with 64x64 png images.

**Comment by ramidzamzam** [comment]
@Faisal-NSU images_data.json is the output of running data_prep.py on your images and txt files. Take a look ...
